import = [
    "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]

[cursor]
style = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "JetBrains Mono"
#family = "Terminus"
style = "Regular"
